# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' An Rcpp Armadillo function to find log10 Bayes factors for an individual gene corresponding to a grid of a mixture normal
#'
#' @param bhat          A double that represents an estimated effect size of a single gene
#' @param sdhat         A double that represents the standard error of the estimated effect size of a single gene
#' @param phi_vec       A k length column vector type that represents the standard deviations of the mixture of normal distributions distribution of the true effect size of an associated gene
#' @return              A k length column vector of log10 Bayes Factors, representing the likelihood of the gene coming from that that component of the mixture normal
compute_log10BF <- function(bhat, sdhat, phi_vec) {
    .Call(`_BagseCpp_compute_log10BF`, bhat, sdhat, phi_vec)
}

#' An Rcpp Armadillo function that computes a weighted sum of log10 Bayes Factors 
#' 
#' @param log10_BFv      A k length column vector with log10 Bayes Factors corresponding to components of the mixture normal for the effect size of a gene
#' @param wv             A k length column vector of weights corresponding to the components of the mixture normal for the effect size of a gene
#' @return               The weighted sum of the log10 Bayes Factors of the components of the mixture normal for the effect size of a gene
weightedlog10BF <- function(log10_BFv, wv) {
    .Call(`_BagseCpp_weightedlog10BF`, log10_BFv, wv)
}

#' Rcpp Armadillo function to compute a vector containing posterior weights for the mixture normal distribution of an associated gene's effect size
#'
#' @param log10_BF_vec           A k length vector of Bayes Factors representing likelihoods of the gene coming from each of the p mixture normal components
#' @param pi_vec                 A k length vector of prior probabilities of the gene coming from each of the p mixture normal components
#' @param pi0                    A double type prior probability of the gene being unassociated 
#' @param log10_NC               A double type number, which is log10 of a normalizing constant, for the logsum of the prior probabilities and the Bayes Factors
#' @return                       A k+1 length vector of posterior probabilities of the gene coming from each component of the mixture normal. The first entry is the posterior probability of the gene being unassociated
computegridwts <- function(log10_BF_vec, pi_vec, pi0, log10_NC) {
    .Call(`_BagseCpp_computegridwts`, log10_BF_vec, pi_vec, pi0, log10_NC)
}

#' An Rcpp Armadillo function to compute an iteration of the key EM algorithm 
#'
#' @param p             A k+2 length column vector, where k is the components in the mixture normal, that contains all the parameters to be estimated, including the enrichment parameters and the mixture normal weights
#' @param BF_matrix     A (n x k) matrix of Bayes Factors, which is the k Bayes Factors representing each mixture normal component for all n genes
#' @param annot_vec     A n length integer vector of 0s and 1s where a 1 represents that the gene is in the gene set of interest
#' @return              A k+2 length column vector with the new parameter estimates, with the first two being the enrichment parameters and the rest being the mixture normal weight estimates
torus_pool_em <- function(p, BF_matrix, annot_vec) {
    .Call(`_BagseCpp_torus_pool_em`, p, BF_matrix, annot_vec)
}

#' An Rcpp Armadillo function to find the log likelihood using the Bayesian model, with a given set of parameters
#'
#' @param p             A k+2 length column vector, where k is the components in the mixture normal, that contains all the parameters, including the enrichment parameters and the mixture normal weights
#' @param BF_matrix     A (n x k) matrix of Bayes Factors, which is the k Bayes Factors representing each mixture normal component for all n genes
#' @param annot_vec     A n length integer vector of 0s and 1s where a 1 represents that the gene is in the gene set of interest
#' @return              A double type representing the log likelihood with this set of parameters
torus_pool_loglik <- function(p, BF_matrix, annot_vec) {
    .Call(`_BagseCpp_torus_pool_loglik`, p, BF_matrix, annot_vec)
}

#' An Rcpp Armadillo function to calculate enrichment parameters, local FDR for all genes, and estimates for the weights of the components for the mixture normal for associated genes
#' @param betahat       An n length column vector containing effect size estimates for all n genes
#' @param sebetahat     An n length column vector containing the standard errors of the effect size estimates for all n genes
#' @param annotation    An n length integer vector of 0s and 1s, with a 1 corresponding to a gene in the gene set of interest
#' @param tol           A double type number corresponding to the threshold for when the EM algorithm should converge. Default is 1e-1
#'
#' @return              A list containing the following variables:
#' * enrichment_est     A 2 length column vector containing the enrichment parameter estimates
#' * effect_est         An column vector containing estimates for the weights of the mixture normal of the effect size for associated genes 
#' * EM                 The raw output from the EM algorithm within this function
#' * ldfr               An n length column vector containing the local FDR for all genes, using enrichment information
torus_cpp <- function(betahat, sebetahat, annotation, tol = 1e-1) {
    .Call(`_BagseCpp_torus_cpp`, betahat, sebetahat, annotation, tol)
}

rcpparma_hello_world <- function() {
    .Call(`_BagseCpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_BagseCpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_BagseCpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_BagseCpp_rcpparma_bothproducts`, x)
}

